### PR TITLE
Fixed a typo in the Readme.md file @SLoP

### PR DESCRIPTION
**Pull request by ishikaanugupta**
In the Readme.md file, the eighth bullet point of WORKING METHOD 'the claim' had been repeated twice. This typo has been rectified.

### CODE REVIEW

**Comment by adithyaanilkumar** [comment]
give @ishikaanugupta 10 points

**Comment by meet59patel** [comment]
@adithyaanilkumar 10 points not being one of the `5, 25, 75, 150` points, your above point award comment was ignored.

**Comment by adithyaanilkumar** [comment]
@meet59patel Thank you for informing me.

**Comment by adithyaanilkumar** [comment]
give @ishikaanugupta 25 points

**Comment by abhinavraj23** [comment]
@adithyaanilkumar this is a readme change and should get 5 points, we are changing it!

**Pull request merged**
