### PR TITLE
first push for landing page

### PR DESCRIPTION
**Pull request by AshutoshDash1999**
- Created landing page according to the Figma design
Screencast from 08-10-20 10 35 24 PM IST

Related #1

### CODE REVIEW

**Comment by adithyaanilkumar** [comment]
give @AshutoshDash1999 150 points

**Comment by adithyaanilkumar** [comment]
Great work! there are a few changes we will be making so illl merge the PR after the landing page is done. Keep pushing changes to the same branch.

**Comment by AshutoshDash1999** [comment]
okay

**Comment by abhinavraj23** [comment]
@adithyaanilkumar this PR should get maximum 75 point, we are changing it!

**Pull request merged**
