### PR TITLE
2nd commit for landing page

### PR DESCRIPTION
**Pull request by AshutoshDash1999**
What's done?
1. Tried to make the landing page as close to the design in desktop.

What's more to do?
1. Try to make 2nd page close to the design.
2. Add those leaf images in the background.
3. Make the website responsive.
4. Add some animations if possible.

Related #1 

Screencast from 04-11-20 06 48 25 AM IST

### CODE REVIEW

**Comment by adithyaanilkumar** [comment]
give @AshutoshDash1999 150 points

**Comment by adithyaanilkumar** [comment]
Could you please make the heights of the carousel div and the step 1,2,3 div the same? Currently it is different for all three. We need to make that uniform.

**Review by adithyaanilkumar — CHANGES_REQUESTED** [review]
Please correct the above.

**Review by AshutoshDash1999 — COMMENTED** [review]
- updated style.css to make the height of carousal, step 1,2,3 same; line 135

**Comment by adithyaanilkumar** [comment]
give @AshutoshDash1999 75 points

**Pull request merged**
