### PR TITLE
3rd commit for landing page

### PR DESCRIPTION
**Pull request by AshutoshDash1999**
- Added one-page scroll effect on About us page

Bugs:
- The background image doesn't fit to the screen.
- The nav bar is behaving as a fixed to the screen.
Screencast from 09-11-20 08 05 03 AM IST

### CODE REVIEW

**Comment by adithyaanilkumar** [comment]
@AshutoshDash1999 Please resize the background image to 1920 * 1080 . The exports on Figma has a different aspect ratio that the one that most computers use/ Also can you take help from @rootnarayan to make the website responsive. That should resolve the background image issue.

**Comment by AshutoshDash1999** [comment]
@adithyaanilkumar How to resize the image to 1920*1080? The pic's size is 1440*1080. Can you add the site link in the description?

**Comment by adithyaanilkumar** [comment]
You can specify the image size in using basic html . Could you please contact @rootnarayan for the same?

**Comment by adithyaanilkumar** [comment]
give @AshutoshDash1999 75 points

**Pull request merged**
